name: Build and release a new version of opencv

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.13.1
        with:
          cmake-version: 3.28

      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout OpenCV
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv
          ref: refs/tags/4.7.0
          path: 'opencv'
          
      - name: Build framework
        working-directory: opencv
        run: |
          pip3 install pathlib
          python3 platforms/ios/build_framework.py --without videoio --without video --iphoneos_archs arm64 --build_only_specified_archs build
        
      - name: Zip artifact
        working-directory: opencv
        run: zip -r opencv2.framework.zip build/opencv2.framework

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: opencv2.framework.zip
          path: opencv/opencv2.framework.zip
          if-no-files-found: error
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: opencv2.framework.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: opencv2.framework.zip
          tag_name: 1.2
